<?xml version="1.0" encoding="utf-8"?><Database Name="Company" Class="CompanyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Company;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Administrare_firma.Properties.Settings" SettingsPropertyName="CompanyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WorkFromHome" Member="WorkFromHomes">
    <Type Name="WorkFromHome">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Work_platform" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Employee_WorkFromHome" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Absence" Member="Absences">
    <Type Name="Absence">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_of_absence" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Start_hour" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="End_hour" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="Employee_Absence" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bonus" Member="Bonus">
    <Type Name="Bonus">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Value" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Necessary_conditions" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="Employee_Bonus" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BussinessTrip" Member="BussinessTrips">
    <Type Name="BussinessTrip">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Start_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="End_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Anticipated_expenses" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Buget" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Importance" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Employee_BussinessTrip" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clocking" Member="Clockings">
    <Type Name="Clocking">
      <Column Name="ID_clocking" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_of_clocking" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Start_hour" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="End_hour" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="Employee_Clocking" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Days_Off" Member="Days_Offs">
    <Type Name="Days_Off">
      <Column Name="ID_days_off" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type_of_days_off" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Begin_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="End_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Employee_Days_Off" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="ID_department" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nume" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descriere" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="ID_department" OtherKey="ID_department" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="First_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CNP" Type="System.String" DbType="Char(13)" CanBeNull="true" />
      <Column Name="Date_of_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Home_address" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Phone_number" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_post" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_department" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Base_salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Contract_period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contract_type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Employee_WorkFromHome" Member="WorkFromHomes" ThisKey="ID" OtherKey="ID_employee" Type="WorkFromHome" />
      <Association Name="Employee_Absence" Member="Absences" ThisKey="ID" OtherKey="ID_employee" Type="Absence" />
      <Association Name="Employee_Bonus" Member="Bonus" ThisKey="ID" OtherKey="ID_employee" Type="Bonus" />
      <Association Name="Employee_BussinessTrip" Member="BussinessTrips" ThisKey="ID" OtherKey="ID_employee" Type="BussinessTrip" />
      <Association Name="Employee_Clocking" Member="Clockings" ThisKey="ID" OtherKey="ID_employee" Type="Clocking" />
      <Association Name="Employee_Days_Off" Member="Days_Offs" ThisKey="ID" OtherKey="ID_employee" Type="Days_Off" />
      <Association Name="Employee_Evaluation" Member="Evaluations" ThisKey="ID" OtherKey="ID_employee" Type="Evaluation" />
      <Association Name="Employee_Evaluation1" Member="Evaluations1" ThisKey="ID" OtherKey="ID_manager" Type="Evaluation" />
      <Association Name="Employee_Training_assignment" Member="Training_assignments" ThisKey="ID" OtherKey="ID_employee" Type="Training_assignment" />
      <Association Name="Employee_User_employee" Member="User_employees" ThisKey="ID" OtherKey="ID_employee" Type="User_employee" />
      <Association Name="Employee_Account" Member="Accounts" ThisKey="ID" OtherKey="EmployeeID" Type="Account" />
      <Association Name="Employee_Request" Member="Requests" ThisKey="ID" OtherKey="RequesterID" Type="Request" />
      <Association Name="Department_Employee" Member="Department" ThisKey="ID_department" OtherKey="ID_department" Type="Department" IsForeignKey="true" />
      <Association Name="Post_Employee" Member="Post" ThisKey="ID_post" OtherKey="ID_post" Type="Post" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Evaluation" Member="Evaluations">
    <Type Name="Evaluation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_of_evaluation" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Start_date_of_evaluation" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="End_date_of_evaluation" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Scor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Feedback" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Future_objectives" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ID_manager" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Evaluation" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
      <Association Name="Employee_Evaluation1" Member="Employee1" ThisKey="ID_manager" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="ID_post" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nume" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descriere" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Level_of_importance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Post_Employee" Member="Employees" ThisKey="ID_post" OtherKey="ID_post" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Level_of_importance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Permissions" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="Role_User_employee" Member="User_employees" ThisKey="ID" OtherKey="ID_role" Type="User_employee" />
    </Type>
  </Table>
  <Table Name="dbo.Training" Member="Trainings">
    <Type Name="Training">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Training_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Begin_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="End_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Training_Training_assignment" Member="Training_assignments" ThisKey="ID" OtherKey="ID_training" Type="Training_assignment" />
    </Type>
  </Table>
  <Table Name="dbo.Training_assignment" Member="Training_assignments">
    <Type Name="Training_assignment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_training" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Employee_Training_assignment" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
      <Association Name="Training_Training_assignment" Member="Training" ThisKey="ID_training" OtherKey="ID" Type="Training" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_employee" Member="User_employees">
    <Type Name="User_employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Last_authentification" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Employee_User_employee" Member="Employee" ThisKey="ID_employee" OtherKey="ID" Type="Employee" IsForeignKey="true" />
      <Association Name="Role_User_employee" Member="Role" ThisKey="ID_role" OtherKey="ID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Employee_Account" Member="Employee" ThisKey="EmployeeID" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Requests" Member="Requests">
    <Type Name="Request">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RequesterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DurationDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Explanation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ReviewedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReviewDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Request" Member="Employee" ThisKey="RequesterID" OtherKey="ID" Type="Employee" IsForeignKey="true" />
      <Association Name="Project_Request" Member="Project" ThisKey="ProjectID" OtherKey="ProjectID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractorCompany" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expenses" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Project_Request" Member="Requests" ThisKey="ProjectID" OtherKey="ProjectID" Type="Request" />
    </Type>
  </Table>
</Database>